<a href="https://colab.research.google.com/github/gerardowarbringer-eng/Programacion-para-Analitica-Descrip-Predict/blob/main/S06_Actividad_02_ALGEBRALINEAL_271770.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**
Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

GERARDO ISIDORO REYES - 271770
---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [20]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [21]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [22]:
# Tu código aquí
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print(norma_A, norma_B, norma_C)

7.449161026585477 6.777167549942971 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [23]:
# Tu código aquí
producto_punto_AB = np.dot(producto_A, producto_B)
producto_punto_AC = np.dot(producto_A, producto_C)

print("Producto punto A·B:", producto_punto_AB)
print("Producto punto A·C:", producto_punto_AC)


# 2. Ángulos en grados
cos_AB = producto_punto_AB / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
cos_AC = producto_punto_AC / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))

angulo_AB = np.degrees(np.arccos(cos_AB))
angulo_AC = np.degrees(np.arccos(cos_AC))

print("Ángulo A-B:", angulo_AB, "grados")
print("Ángulo A-C:", angulo_AC, "grados")

Producto punto A·B: 50.46
Producto punto A·C: 26.5
Ángulo A-B: 1.7745815839558179 grados
Ángulo A-C: 47.22509268261831 grados


---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [24]:
# Tu código aquí

# Normalizar los vectores
producto_A_unitario = producto_A / np.linalg.norm(producto_A)
producto_B_unitario = producto_B / np.linalg.norm(producto_B)
producto_C_unitario = producto_C / np.linalg.norm(producto_C)

# Imprimir los vectores normalizados
print("Producto A normalizado:", producto_A_unitario)
print("Producto B normalizado:", producto_B_unitario)
print("Producto C normalizado:", producto_C_unitario)

# Verificar que sus normas sean 1
print("Normalizado de A:", np.linalg.norm(producto_A_unitario))
print("Normalizado de B:", np.linalg.norm(producto_B_unitario))
print("Normalizado de C:", np.linalg.norm(producto_C_unitario))

Producto A normalizado: [0.60409488 0.42957858 0.67121653]
Producto B normalizado: [0.59021707 0.41315195 0.69350506]
Producto C normalizado: [0.19090089 0.95450444 0.22908106]
Normalizado de A: 1.0
Normalizado de B: 1.0
Normalizado de C: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [25]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [26]:
# Tu código aquí
print("M * P =")
print(M * P)

print("M @ P =")
print(M @ P)

print("P @ M =")
print(P @ M)
#No me dió el mismo resultado

M * P =
[[3. 0.]
 [0. 6.]]
M @ P =
[[3.  2. ]
 [1.5 6. ]]
P @ M =
[[3.  1.5]
 [2.  6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [27]:
# Tu código aquí
det_M = np.linalg.det(M)
print("Determinante de M:", det_M)

M_inv = np.linalg.inv(M)
print("Inversa de M:")
print(M_inv)

identidad = M @ M_inv
print("M @ M_inv:")
print(identidad)

Determinante de M: 5.000000000000001
Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]
M @ M_inv:
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [28]:
b = np.array([180, 300])

# Resolver el sistema Mx = b
x = np.linalg.solve(M, b)

print("Unidades de cada insumo:", x)

# Verificar la solución
verificacion = M @ x
print("M @ x =", verificacion)
print("¿El resultado coincide con b?", np.allclose(verificacion, b))
# Tu código aquí


Unidades de cada insumo: [48. 84.]
M @ x = [180. 300.]
¿El resultado coincide con b? True


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [29]:
# Tu código aquí
dist_AB = np.linalg.norm(producto_A - producto_B)
dist_AC = np.linalg.norm(producto_A - producto_C)

# 2. Similitud coseno
sim_AB = np.dot(producto_A, producto_B) / (
    np.linalg.norm(producto_A) * np.linalg.norm(producto_B)
)

sim_AC = np.dot(producto_A, producto_C) / (
    np.linalg.norm(producto_A) * np.linalg.norm(producto_C)
)

# Mostrar resultados
print("Distancia A-B:", dist_AB)
print("Distancia A-C:", dist_AC)
print("Similitud coseno A-B:", sim_AB)
print("Similitud coseno A-C:", sim_AC)

Distancia A-B: 0.7071067811865476
Distancia A-C: 5.470831746635972
Similitud coseno A-B: 0.9995203969214979
Similitud coseno A-C: 0.6791199021706347


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.